language: node_js
node_js:
  - "6.8.0"

script:
  - npm install
  - npm run build
  - npm run test-cov
after_success:
- bash <(curl -s https://codecov.io/bash) -t 7e7082e9-fe6b-4a24-936c-b5c56708233b
